name: flutter_chat_demo
description: This is the demo for chat app by Flutter

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.4
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  shared_preferences: ^2.0.15
  firebase_storage: ^11.0.4
  firebase_messaging: ^14.0.4
  flutter_local_notifications: ^12.0.3
  photo_view: ^0.14.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

environment:
  sdk: ">=2.17.6 <3.0.0"