// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAidd5ocNRBd217zciGPHAqVGTmho691A4',
    appId: '1:844651159611:android:51179eda4f7f1562b07c1e',
    messagingSenderId: '844651159611',
    projectId: 'chatapp-3389b',
    databaseURL: 'https://chatapp-3389b-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-3389b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATTbv_keKHCoPFKM0j8YVm9Ve8CElkc10',
    appId: '1:844651159611:ios:944d59fc1d944ac6b07c1e',
    messagingSenderId: '844651159611',
    projectId: 'chatapp-3389b',
    databaseURL: 'https://chatapp-3389b-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-3389b.appspot.com',
    iosClientId: '844651159611-fiqikn0g9dpc58brmrinq1s14mbrpfg4.apps.googleusercontent.com',
    iosBundleId: 'com.duytq.flutterchatdemo',
  );
}
